model:
  base_learning_rate: 4.5e-06
  target: taming.models.clip_transformer.CLIPCond
  params:
    pkeep: 0.5
    ckpt_path: logs/2022-03-18T16-10-49_ffhq_thumbnails_transformer/testtube/version_0/checkpoints/epoch=12-step=1468.ckpt
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 1024
        block_size: 512
        n_layer: 24
        n_head: 16
        n_embd: 512
        embd_pdrop: 0.1
        resid_pdrop: 0.1
        attn_pdrop: 0.1
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: logs/2022-03-18T11-15-13_custom_vqgan/testtube/version_0/checkpoints/epoch=22-step=10372.ckpt
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          double_z: False
          z_channels: 256
          resolution: 128
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    cond_stage_config:
      target: taming.models.dummy_cond_stage.DummyCondStage
      params:
        conditional_key: objects_bbox

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 512
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: train.txt
        size: 64
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: test.txt
        size: 64
